### ISSUE TITLE
Timeout exception, send button doesn't refresh .

### ISSUE THREAD

**Issue by Emersonksc** [InterestingDarkness/ChatSydney#2]
D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\python.exe D:\programFiles\programmingLanguage\pythonProject\ChatSydney\main.py 
Go to http://localhost:65432 to start chatting!
connection handler failed
Traceback (most recent call last):
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
**ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:1007)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\backends\asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\anyio\streams\tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\anyio\_backends\_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\backends\asyncio.py", line 78, in start_tls
    raise exc
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\backends\asyncio.py", line 68, in start_tls
    with anyio.fail_after(timeout):
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\anyio\_core\_tasks.py", line 118, in __exit__
    raise TimeoutError
**TimeoutError**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\backends\asyncio.py", line 66, in start_tls
    with map_exceptions(exc_map):
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "D:\programFiles\programmingLanguage\pythonProject\ChatSydney\main.py", line 15, in handle_client
    async for response in process_message(user_message, context):
  File "D:\programFiles\programmingLanguage\pythonProject\ChatSydney\main.py", line 22, in process_message
    chatbot = await Chatbot.create(cookie_path="D:\programFiles\programmingLanguage\pythonProject\ChatSydney\cookies.json")
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\EdgeGPT.py", line 626, in create
    await _Conversation.create(self.cookies, self.proxy),
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\EdgeGPT.py", line 385, in create
    response = await client.get(
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\programFiles\programmingLanguage\PythonALL\anaconda\envs\reverse_engineering\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
**httpx.ConnectTimeout**
### =================================================================
没有处理网络超时异常，界面发送按钮会一直卡住，没有刷新。

**Comment by InterestingDarkness** [comment]
https://github.com/InterestingDarkness/ChatSydney/commit/91276abc0b7144f6b4020b7e156277fe1fe7f1fd
should fix
